version: "3.9"

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql8_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=topsecret
      - MYSQL_PASSWORD=topsecret
      - MYSQL_USER=soapbox
      - MYSQL_DATABASE=soapbox

volumes:
  mysql8_data:
